name: Sanity Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: arduino/setup-task@v1
      - name: Prepare dev env
        run: task dependency-install
      - name: Lint and tests
        run: |
          source .venv/bin/activate
          task test

  build-test:
    name: "Build wheel"
    needs:
      - pre-commit
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: arduino/setup-task@v1
      - run: task dependency-install
      - run: uv build
