name: Release
on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: trufflehog

  release:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: pip install uv
      - uses: arduino/setup-task@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task dependency-install
      - uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: false
